security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]

    firewalls:
        api:
            pattern: ^/api
            stateless: false
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/security/request/reset, roles: PUBLIC_ACCESS }
        - { path: ^/api/security/reset/password, roles: PUBLIC_ACCESS }
        - { path: ^/api/management/users/create, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }